apiVersion: v2
appVersion: 7.0
name: wg-easy
version: 0.0.2
description: wg-easy description todo
dependencies:
- name: replicated-library
  #repository: https://replicatedhq.github.io/helm-charts
  repository: file://../../../helm-charts-library/charts/replicated-library/
  version: '^0.6.1'
home: https://github.com/replicatedhq/replicated-starter-helm/charts/tree/main/
kubeVersion: '>=1.20.0-0'
